# audit_tool/reports/markdown_report.py
from audit_tool.checks.models import AuditReport, Severity


def generate_markdown(report: AuditReport) -> str:
    """
    Generate a Markdown audit report from an AuditReport object.

    Args:
        report: Completed AuditReport with all findings

    Returns:
        Markdown formatted string
    """
    summary = report.summary()
    lines = []

    # header
    lines.append(f"# Network Configuration Audit Report")
    lines.append(f"**Network:** {report.network_name}")
    lines.append(f"**Generated:** {report.generated_at}")
    lines.append(f"**Audit Mode:** Offline (config file analysis)")
    lines.append("")

    # executive summary
    lines.append("## Executive Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🔴 HIGH   | {summary['high']} |")
    lines.append(f"| 🟡 MEDIUM | {summary['medium']} |")
    lines.append(f"| 🔵 LOW    | {summary['low']} |")
    lines.append(f"| ℹ️ INFO   | {summary['info']} |")
    lines.append(f"| **TOTAL** | **{summary['total_findings']}** |")
    lines.append("")

    # overall status
    if summary['high'] > 0:
        lines.append("> ⚠️ **Action Required** — HIGH severity findings detected.")
    elif summary['medium'] > 0:
        lines.append("> 🔍 **Review Required** — MEDIUM severity findings detected.")
    else:
        lines.append("> ✅ **No significant issues found.**")
    lines.append("")

    # findings by check
    lines.append("## Findings")
    lines.append("")

    for result in report.check_results:
        lines.append(f"### {result.check_name.replace('_', ' ').title()}")
        lines.append(f"**Status:** {result.status.value} | "
                     f"**Devices Checked:** {result.devices_checked}")
        lines.append("")

        if not result.findings:
            lines.append("✅ No issues found.")
            lines.append("")
            continue

        # findings table
        lines.append("| Severity | Device | Finding |")
        lines.append("|----------|--------|---------|")
        for f in result.findings:
            severity_icon = {
                Severity.HIGH:   "🔴 HIGH",
                Severity.MEDIUM: "🟡 MEDIUM",
                Severity.LOW:    "🔵 LOW",
                Severity.INFO:   "ℹ️ INFO"
            }.get(f.severity, f.severity.value)
            lines.append(f"| {severity_icon} | {f.device} | {f.message} |")

        lines.append("")

        # detailed findings
        lines.append("#### Details")
        lines.append("")
        for f in result.findings:
            lines.append(f"**{f.device}** — {f.message}")
            lines.append(f"> {f.detail}")
            lines.append("")

    # recommendations
    lines.append("## Recommendations")
    lines.append("")

    high_findings = report.findings_by_severity(Severity.HIGH)
    medium_findings = report.findings_by_severity(Severity.MEDIUM)

    if high_findings:
        lines.append("### Immediate Action Required")
        for f in high_findings:
            lines.append(f"- **{f.device}**: {f.message}")
        lines.append("")

    if medium_findings:
        lines.append("### Review and Verify")
        for f in medium_findings:
            lines.append(f"- **{f.device}**: {f.message}")
        lines.append("")

    lines.append("---")
    lines.append("*Report generated by Network Config Audit Tool*")

    return "\n".join(lines)


def save_markdown(report: AuditReport, output_path: str) -> None:
    """
    Generate and save Markdown report to file.

    Args:
        report: Completed AuditReport
        output_path: Path to save the .md file
    """
    content = generate_markdown(report)
    with open(output_path, "w") as f:
        f.write(content)
    print(f"Report saved to: {output_path}")
